Repository appuio/terraform-rancher-cloudscale, pull requests merged in 2022-07, with the labels that each got.

#23 Enable etcd backup to S3 by default
  rancher.tf
  variables.tf
Labels: enhancement, change

#24 Fix terraform dependencies
  rancher.tf
Labels: bug

#25 Make kubelet args configurable
  rancher.tf
  variables.tf
Labels: enhancement

#26 Fix cloud credential name for etcd S3 backup
  rancher.tf
Labels: bug
